const menu = [
  {
    id: 1,
    name: 'Duman',
    sex: 'male',
    age: 9,
    address: 'Ankara, Turkey',
    phone: 5385837763,
    img: 'https://prnt.sc/11fqpmg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    name: 'Anten',
    sex: 'female',
    age: 10,
    address: 'İzmir, Turkey',
    phone: 5385837763,
    img: 'https://prnt.sc/11fqtei',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 3,
    name: 'Isot',
    sex: 'male',
    age: 7,
    address: 'Antalya, Turkey',
    phone: 5385837763,
    img: 'https://prnt.sc/11fr49q',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 4,
    name: 'Kahve',
    sex: 'male',
    age: 8,
    address: 'Mersin, Turkey',
    phone: 5385837763,
    img: 'https://prnt.sc/11frihv',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 5,
    name: 'Kori',
    sex: 'female',
    age: 5,
    address: 'Kocaeli, Turkey',
    phone: 5385837763,
    img: 'https://prnt.sc/11frog4',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 6,
    name: 'Patik',
    sex: 'male',
    age: 4,
    address: 'Ankara, Turkey',
    phone: 5385837763,
    img: 'https://prnt.sc/11frvks',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 7,
    name: 'Uzum',
    sex: 'female',
    age: 7,
    address: 'İstanbul, Turkey',
    phone: 5385837763,
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 8,
    name: 'Pasa',
    sex: 'male',
    age: 5,
    address: 'Adana, Turkey',
    phone: 5385837763,
    img: 'https://prnt.sc/11fsouo',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 9,
    name: 'Kete',
    sex: 'female',
    age: 6,
    address: 'Aydın, Turkey',
    phone: 5385837763,
    img: 'https://prnt.sc/11ft0kg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 10,
    name: 'Loki',
    sex: 'female',
    age: 5,
    address: 'Konya, Turkey',
    phone: 5385837763,
    img: 'https://prnt.sc/11ftci9',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
];
export default menu;
